### PR TITLE
clear the contents of a session included as a method

### LINKED ISSUE #34: unable to use session after destroy
Dunno if this is a bug per se, but surprised me.  After running an `env.session.destroy` if I access the session again in that request:

```
get "/logout" do |env|
  env.session.destroy
  env.session.string("flash", "successfully logged out")
  env.redirect "/login"
end
```

I get this:

```
Missing hash key: "9312da9064daec185cc58cb1bf3937f4" (KeyError)
0x82ec567: *Hash(String, String) at /opt/crystal/src/hash.cr 124:9
0x82ec42c: *Hash(String, String) at /opt/crystal/src/hash.cr 61:5
0x83289f8: *Session::MemoryEngine#string:String at /kemal_server/lib/kemal-session/src/kemal-session/engines/memory.cr 136:5
0x83295ef: *Session#string:String at .../kemal-session/src/kemal-session/engine.cr 48:3

```

(for followers, the work around is to not reuse flash anymore forthat request, it creates a new session on the next request seemingly.

### PR DESCRIPTION
**Pull request by neovintage**
Fixes #34 

/cc @sdogruyol

### CODE REVIEW

**Comment by sdogruyol** [comment]
Thanks @neovintage, can you solve the conflict please?

**Comment by neovintage** [comment]
@sdogruyol fixed

**Comment by sdogruyol** [comment]
Not sure why but Travis is angry @neovintage

**Comment by neovintage** [comment]
This stinks. I can't reproduce this on my machine. The only differences I can see are the llvm version used for compilation. As of this point, ideas are welcome.

**Comment by neovintage** [comment]
I think what's happening is that I'm running into issue #37. It's clear that on travis its not deserializing correctly. I'm not sure why it's different on my machine. I'll need to fix that first before introducing this.

**Comment by neovintage** [comment]
I'm starting over on this branch this is totally weird.

**Pull request closed without merging**
