### PR TITLE
Session Administrative Functions

### PR DESCRIPTION
**Pull request by neovintage**
This takes care of the use case where you want to remove the session from session storage and unset the session from the user's browser. Here's how you'd use it in kemal:

```crystal
require "kemal"
require "kemal-session"

delete "/logout" do |env|
  env.session.remove
end
```

If you have administrative actions that need to be taken against session storage, your code should drop down to the engine to deal with that:

```crystal
Session.config.engine.remove("asdfasdfasd")
```

I'll update the redis storage engine if this PR looks good.

### CODE REVIEW

**Comment by Thyra** [comment]
I think the functionality is important but I would rather call it _destroy_ instead of _remove_. This is how it would be called in active-record terms and is also what is used in [PHP](http://php.net/manual/en/function.session-destroy.php).
Secondly I think that `Session.config.engine.remove("asdfasdfasd")` is a bit complicated. My original plan (that is also still on the roadmap) was something active-record like: Session.all returns an array with all active sessions (passed through from the engine), Session.get(session_id) or Session.find(session_id) returns one single session object identified by the session_id. As there can only be one active engine at any given time, the session class can handle the interaction with the engine itself, no need to bother the user. 
With these methods removal would already be possible because the session object has a _destroy_ method, but Session.remove("asdfasdf") could be used as a shortcut (Or maybe also Session.destroy("asdfasdf") in this case?). What do you think, @neovintage?

**Comment by neovintage** [comment]
@Thyra Renaming the method from `remove` => `destroy` is a non-issue. I think that's fine. From this point forward, I'll refer to the method as `destroy` for clarity-sake.

With the solution you're proposing, it feels like we're conflating two different problems and how to solve them. When I posted my first comment, the initial problem that I had in mind was when a logout or sign out path was implemented in kemal, the intention the developer had was to invalidate the session so that the user of that web app could no longer access paths that required authorization. My assumption is that invalidating the session required two distinct steps, deleting the session from the store and clearing out the session_id cookie in the user's browser. When the request is issued in kemal the session object is hydrated as part of the HTTP::Server::Context. With that being there, I figured an instance method call would be appropriate to destroy the session and take care of the session_id cookie. I'm not sure about skipping invaliding the session_id cookie but I think it might be better if we do invalidate it. (I could be wrong here and would like to discuss further. I believe this is the basis of the divergence)

Based on my original assumptions, the implementation you're proposing feels more like administrative functions relative to all of the sessions as part of the application. Given the first problem I was trying to solve for, if I issue a class method on session, I wouldn't have the information about the user's session_id cookie and would be unable to invalidate it. But, if we make a distinction between calling `destroy` on the session object itself vs a class method, we could say that the instance method takes care of the session_id cookie while the class methods dont. I wasn't sure about dropping down to the engine to remove the session from the store itself. I posted it as part of the PR to see what kind of feedback I'd get. 

I think `Session.get(session_id)` works and would be great. `Session.all` makes me a little nervous because it could result in very large arrays being returned. Plus for datastores like Redis, it would require scanning all keys to produce that array. yuck. but that's only one data point

**Comment by Thyra** [comment]
@neovintage You're absolutely right, I had administrative functions in mind ;-). I felt that it would be important to make these design decisions before implementing something and then later having to struggle with adding more functionality.

You're bringing up an issue that I had not thought about at all: When a request destroys any session other than its own, it cannot delete the cookie from the client that is attached to this session: If for example an administrator decides to destroy session xyz, Kemal does not reach out to the corresponding user by itself and tells it that his session is now invalid. It simply deletes the session record from the server. This is not perfect, but I think it is not really a problem, either; we already have the same case with the garbage collector: When a session is removed after x minutes of inactivity, the user is also not notified. If he makes another request, Kemal will simply notice that the given session_id does not exist on the server in which case it just creates a new (empty) session for the given session_id. I do not think this is a problem in any way, as there is no authentification info left (user_id etc.). PHP's session_destroy does the same, by the way: It also just deletes the session from the server without telling the client to remove the cookie. So my solution right now would be to only delete the session storage from the server and not worry about the cookies.

`Session.all` is certainly neccessary for, let's say, an administrative interface, but I could imagine something like SQL's `LIMIT`: `Session.all(300,100)` returns 100 sessions starting with the 300th (sorted by session_id).

**Comment by neovintage** [comment]
@Thyra For `Session.all` what if there was an option to pass a block? If no block is passed then the entire array would be returned, otherwise the engine could use the block and iterate over the sessions without bringing all of them in memory.

**Comment by Thyra** [comment]
@neovintage Yes, I think that's a wonderful idea!

**Comment by neovintage** [comment]
@Thyra ok. let me take another pass at this and we'll discuss again.

**Comment by sdogruyol** [comment]
I really like what i see here 👍

**Comment by neovintage** [comment]
@Thyra oh ha. I forgot that github updates the PR. I'm not quite done. I've been switching between machines and needed to keep both in sync. :-)

I already changed point 1 on my local machine. Just didn't push it. I will look into the second point. That didn't occur to me.

**Comment by neovintage** [comment]
@Thyra ok. I ran into one issue while testing that brings up something that's related. One of the problems I was having is that when a session is valid in terms of the cookie that's signed on the browser and its a new session, nothing's actually saved in the engine unless you *actually* save something else in session storage by calling one of the other methods like `context.session.int("asdf", 1234)`. So the question is posed:

when a new session is created (https://github.com/kemalcr/kemal-session/blob/master/src/kemal-session/base.cr#L22-L24), should we instantiate an empty session in session storage?

Personally, I think we should so that session storage has a closer to true representation of the number of active sessions. I would propose that the section I'm referring when a new session is created we do something like this:

```
if id.nil? || !valid
  id = SecureRandom.hex
  Session.config.engine.build(id)
end
```

**Comment by Thyra** [comment]
@neovintage Yes, I completely agree and I think your proposal is the right way to do it. I would be a little bit more verbose with the method name, though. Something like `.create_session` would be more clear to people who don't know the code or haven't read this PR.

**Comment by neovintage** [comment]
@sdogruyol @Thyra I think we're ready for a final review.

**Comment by sdogruyol** [comment]
I think this is great 👍  However we need to update all the session engines for the new API right?

**Comment by Thyra** [comment]
@sdogruyol Yes, that's correct. I would also make this version 0.5 because of that.

**Comment by Thyra** [comment]
@neovintage What do you think about setting `@context` to nil instead of creating a fake context when initializing a session by its id? In my opinion it would be clearer and provide less possibilities for bugs and confusion to sneak in.

Other than that I think this is absolutely wonderful and I want to thank you again for the huge amount of work and thought you put into it! The only thing left to do then would be to update the documentation and inform the users about the new functions but maybe @sdogruyol can help you with that ;-).

**Comment by neovintage** [comment]
If @sdogruyol is cool w/ the nil then I can do it. I'm a little hesitant on it thats why I want another opinion.

**Comment by Thyra** [comment]
@neovintage If you're hesitant don't let us talk you into it, maybe I am missing something. What don't you like about it?

**Comment by neovintage** [comment]
@Thyra It could be unfounded but I'm thinking about the nil checks that have to be done now that context can be two different types. I can spike it out to see how it looks.

**Comment by Thyra** [comment]
@neovintage If I see correctly, there is only one: in base.cr#66 you'd have to go from
```crystal
    if @context.response.cookies.has_key?(Session.config.cookie_name)
      @context.response.cookies[Session.config.cookie_name].value = ""
    end
```
to
```crystal
    if @context
      @context.response.cookies[Session.config.cookie_name].value = ""
    end
```
But the `initialize(@context)` method would have to be changed to `initialize(context)`, perform all the operations on `context` and then finally set `@context = context`, that is true...

**Comment by neovintage** [comment]
@Thyra i took a stab at it. check out the latest.

**Comment by Thyra** [comment]
@neovintage I think this complication is really not needed: in line 66 `if @context` is sufficient and the initialize method also doesn't have to be changed (see my previous comment for both).

**Comment by neovintage** [comment]
@Thyra i tried leaving the `initialize(@context)` and changing the program at line 66. It resulted in compiler errors. I can change the method at line 66 up a little but I think my last pass is sufficient.

**Comment by Thyra** [comment]
@neovintage Really? OK, then let's leave it at that for now. I think it's also time to finally merge this thing ;-). Unfortunately I can't do it as I don't have the rights on this rep, but @sdogruyol can, if he has no further requests.

**Comment by sdogruyol** [comment]
Great job @neovintage, @Thyra 🎉  Thank you 🙏

**Comment by sdogruyol** [comment]
Just release [v0.5.0](https://github.com/kemalcr/kemal-session/releases/tag/v0.5.0). 

Now we need to update the documentation and sessions engines 😄

**Pull request merged**
