### PR TITLE
add a clear method

### PR DESCRIPTION
**Pull request by neovintage**
Will destroy the current session in session storage and then creates a new session id and storage for the current response cycle.

### CODE REVIEW

**Comment by sdogruyol** [comment]
Travis is failing again 😢

**Comment by neovintage** [comment]
I'm calling the new method `.reset`. This will destroy the current session in session storage and then create a new one with a new session id. I think this will take care of any session fixation attacks.

I also fixed travis. It was super weird. The way the files were getting executed were different on my mac vs travis. On travis, file_spec.cr got executed first and this resulted in FileStore being used through out all of the specs instead of the memory engine. All fixed now. It only took me pulling down a docker image :-(

/cc @sdogruyol

**Comment by neovintage** [comment]
We should also add some extra testing to FileStore to make sure StorableObject is behaving properly. Will likely save for another PR.

**Comment by sdogruyol** [comment]
Great catch 🔥 
Why do you rename `clear` to `reset` though?

**Comment by neovintage** [comment]
`clear` to me means that we’re wiping the session and that the current session id could persist once calling the command. `reset` implies that we’re starting over on the session. Since I’m recreating a session id during this method call, I went with `reset`. In other web frameworks, `reset` and `reload` seems to be the pervasive names to mean changing the session id and emptying out session storage.

**Comment by sdogruyol** [comment]
Thanks @neovintage 💯  LGTM 👍

**Pull request merged**
